### ISSUE TITLE
If testruns fails before the repository is cloned, it deletes the cwd

### ISSUE THREAD

**Issue by andreieftimie** [mozilla/mozmill-automation#141]
If the testrun fails before the tests repository is properly cloned the current working directory will be deleted. This has a potentially very damaging outcome.

We stumbled across this some time ago. See #99

Where this fails:
https://github.com/mozilla/mozmill-automation/blob/f50a9f808fe54ee2996fba9cb19f8deb486ee6ec/mozmill_automation/repository.py#L85-L88

Where `path` is generated from cwd + repo
https://github.com/mozilla/mozmill-automation/blob/f50a9f808fe54ee2996fba9cb19f8deb486ee6ec/mozmill_automation/repository.py#L30-L33

**Comment by whimboo** [comment]
We are going to discontinue Mozmill in favor of [Firefox UI Tests](https://github.com/mozilla/firefox-ui-tests). So I'm going to wont fix this issue.
