### ISSUE TITLE
Update all docstrings to be accurate

### ISSUE THREAD

**Issue by davehunt** [mozilla/mozmill-automation#35]
I noticed that some of the docstrings are currently incorrect. For example:

    class RemoteTestRun(TestRun):
        def run_tests(self):
            """ Execute the normal and restart tests in sequence. """

This should be 'Execute the remote tests'. There may be other docstrings that need updating.

**Comment by simar7** [comment]
I can take over this, I have a Pull Request ready to be merged in!

PR: https://github.com/mozilla/mozmill-automation/pull/203

**Comment by whimboo** [comment]
We are going to discontinue Mozmill in favor of [Firefox UI Tests](https://github.com/mozilla/firefox-ui-tests). So I'm going to wont fix this PR.
