### ISSUE TITLE
URL sent using --report='http://mozmill-crowd.blargon7.com/db' doesnt handle link properly in report generation

### ISSUE THREAD

**Issue by sant0sh** [mozilla/mozmill-automation#58]
When sending results to the report server using --report, testrun.py cannot handle the link properly when no forward slash is appended in the link.
eg. --report='http://mozmill-crowd.blargon7.com/db'

**Comment by whimboo** [comment]
We are going to discontinue Mozmill in favor of [Firefox UI Tests](https://github.com/mozilla/firefox-ui-tests). So I'm going to wont fix this PR.
